server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 3


  datasource:
    url: jdbc:mysql://localhost:3306/ai?useSSL=false&serverTimezone=Asia/Shanghai更改自己的数据库端口和名字
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



ali:
  api-key: //前往阿里云百炼平台申请自己的api
  endpoint: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation


logging:
  level:
    org.example.mapper: debug
    com.baomidou.mybatisplus: debug
